[package]
name = "text2num-rs"
version = "1.5.0"
authors = ["Romuald Texier-Marcad√© <r.texiermarcade@allo-media.fr>"]
edition = "2018"

[lib]
name = "text2num"

[dependencies]
unicode-segmentation = "1.6"
phf = { version = "0.8", features = ["macros"] }
